### ISSUE TITLE
Improve error handling for macOS executables to avoid LSOpenURLsWithRole()

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase-macOS-app-template#1]
A commonly reported error for macOS users is:

     LSOpenURLsWithRole() failed with error -10810

This is a generic macOS error that is essentially saying "I couldn't start the app". However, it isn't very helpful, doesn't indicate a next step, and it masks a number of possible problems:

1) The macOS template has a bug in it (e.g., referencing the wrong binary as in beeware/briefcase#57)
2) A bug in the user's requirements list - required libraries haven't been installed
3) A bug in the user's code (e.g., a syntax error in their app).

We need to add better error handling to the macOS app entry point. The script that invokes Python should catch return codes and display a dialog when python fails to start, or raises an error.

**Comment by beckernick** [comment]
Just as a note, I suspect this also can occur due to using an unsupported macOS version. I'm running Yosemite 10.10.5 and get this error while executing `briefcase run` from Tutorial 3.

Inspection ultimately gives this traceback:

```
(base) nickbecker ~ $ /Users/nickbecker/Development/beeware-tutorial/helloworld/macOS/Hello\ World.app/Contents/MacOS/Hello\ World ; exit;
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/nickbecker/Development/beeware-tutorial/helloworld/macOS/Hello World.app/Contents/Resources/Support/bin/python3
  Expected in: /usr/lib/libSystem.B.dylib
```

`_clock_gettime` apparently wasn't added until mac OS 10.12. If this is a requirement, it might be beneficial to note a minimum mac OS version.

**Comment by freakboy3742** [comment]
Thanks for the report! The support libraries *should* be compiled using 10.10 APIs, so we've clearly made an error somewhere. It's good to know this is also a potential source of the error (so we can add it as one of the diagnostic options), but there is clearly something that needs to be fixed on the [Python-Apple-support](https://github.com/beeware/Python-Apple-support) repository. If you could open a ticket there, that would be most appreciated!

**Comment by freakboy3742** [comment]
The app template now includes a crash handler; if the app fails to start, a dialog will be shown displaying the traceback of the problem that occurred.
