### ISSUE TITLE
Add support for macOS Darkmode

### ISSUE THREAD

**Issue by jnnkB** [beeware/briefcase-macOS-app-template#2]
I packaged my macos toga app with briefcase. But unfortunately the window of the packaged app doesn't adapt to dark mode even thought it did before packaging. I used toga 0.3.0.dev11 and briefcase 0.2.9. The programm doesn't show any error messages.

**Comment by freakboy3742** [comment]
From my testing, this was enabled automatically when we moved to the binary-based bootstrap.
