### ISSUE TITLE
Packaged app binary is signed

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase-macOS-app-template#5]
**Describe the bug**

Reported via @davidfokkema on Gitter

The app binary that is contained in the app template is partially signed. This causes problems when loading some binary packages, as the signature doesn't validate.

**To Reproduce**

1. Generate a new project using Toga as the UI
2. Add `kiwisolver` as a dependency (this is a binary module), and add `import kiwisolver` to the top of `app.py`.
3. `briefcase create`
4. `briefcase run`

**Expected behavior**

The app should start.

However, it won't; if you check the console logs, you'll see a message about "...Contents/Resources/app_packages/kiwisolver.cpython-39-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed."

**Environment:**
 - Operating System: macOS
 - Python version: 3.9
 - Software versions: 
   - Briefcase: 0.3.5
   - macOS app template 3.9-b1
   - 
**Additional context**

Running `codesign --remove-signature macOS/app/...` on the binary appears to resolve the problem.

**Comment by davidfokkema** [comment]
Great, thanks! 🎉
