### ISSUE TITLE
README incorrectly says that the entry point is a shell script

### ISSUE THREAD

**Issue by jjasghar** [beeware/briefcase-macOS-app-template#62]
### Describe the bug

It seems you claim this is a `bash` script, but it seems it's a binary.

### Steps to reproduce

Open the file, and notice a bunch of @@@@@

### Expected behavior

A bash script.
```
xxx-xxx: Mach-O 64-bit executable arm64
```

### Environment

- Operating System: MacOS
- Python version: 3.11
- Software versions:
  - Briefcase: newest

### Logs

```

```

**Comment by jjasghar** [comment]
Referenced here: https://github.com/beeware/briefcase-macOS-app-template/blob/main/README.rst?plain=1#L122-L125

**Comment by freakboy3742** [comment]
Thanks for the report; it looks like the README has gotten a little stale. The file that is referenced doesn't even exist in the repository any more (as of a little over a month ago) - and even then, it hasn't been a bash script for almost 2 years.
