### ISSUE TITLE
Same error as CI

### ISSUE THREAD

**Issue by john0isaac** [beeware/briefcase-macOS-app-template#65]
### Describe the bug

I tried to use the command create but I'm receiving the same errors as your CI.

### Steps to reproduce

execute `briefcase create`

### Expected behavior

It doesn't show errors

### Environment

- Operating System: macOS 14.6.1 (23G93)
- Python version: 3.10.11
- Software versions:
  - Briefcase: 0.1.dev4482+g3f77425.d20240824

### Logs

```
[hello-cli] Generating application template...
Using app template: https://github.com/beeware/briefcase-macOS-app-template.git, branch v0.1
Template branch v0.1 not found; falling back to development template
Using existing template (sha e684683a598c5b4175123d63b720010c6b873fd6, updated Fri Aug 16 06:15:11 2024)

[hello-cli] Installing support package...
Using support package https://briefcase-support.s3.amazonaws.com/python/3.10/macOS/Python-3.10-macOS-support.b9.tar.gz
Python-3.10-macOS-support.b9.tar.gz already downloaded
Unpacking support package... done
Copying standard library into app bundle... done

[hello-cli] Installing stub binary...
Using stub binary https://briefcase-support.s3.amazonaws.com/python/3.10/macOS/Console-Stub-3.10-b9.zip
Console-Stub-3.10-b9.zip already downloaded
Installing stub binary... done

The app template used to generate this app is not compatible with this version
of Briefcase.

If the app was generated with an earlier version of Briefcase using the default
Briefcase template, you can run:

     $ briefcase create macOS app

to re-generate your app with a compatible version of the template.

If you are using a custom template, you'll need to update the template to correct
any compatibility problems, and then add the compatibility declaration.
```

**Comment by john0isaac** [comment]
I installed the latest briefcase 0.3.19 and everything works now, sorry!

**Comment by freakboy3742** [comment]
For the sake of posterity - the error you were seeing was caused because you were using a development version of Toga, but your GitHub clone *didn't* include tags. As a result, the version number was identified as 0.1.dev... rather than 0.3.19.dev. Since the Briefcase version is used to determine the template branch, and the Briefcase version in development checkouts is determined using `setuptools-scm`, it's important that you have current tags in your clone.
